[2025-02-06T08:27:14.186+0000] {processor.py:186} INFO - Started process (PID=68) to work on /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T08:27:14.188+0000] {processor.py:914} INFO - Processing file /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-06T08:27:14.190+0000] {logging_mixin.py:190} INFO - [2025-02-06T08:27:14.189+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T08:27:14.203+0000] {logging_mixin.py:190} INFO - [2025-02-06T08:27:14.202+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-06T08:27:14.203+0000] {logging_mixin.py:190} INFO - [2025-02-06T08:27:14.203+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-06T08:27:14.204+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T08:27:14.223+0000] {processor.py:208} INFO - Processing /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.041 seconds
[2025-02-06T08:30:53.234+0000] {processor.py:186} INFO - Started process (PID=68) to work on /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T08:30:53.235+0000] {processor.py:914} INFO - Processing file /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-06T08:30:53.238+0000] {logging_mixin.py:190} INFO - [2025-02-06T08:30:53.237+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T08:30:53.242+0000] {logging_mixin.py:190} INFO - [2025-02-06T08:30:53.241+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-06T08:30:53.242+0000] {logging_mixin.py:190} INFO - [2025-02-06T08:30:53.242+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-06T08:30:53.243+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T08:30:53.267+0000] {processor.py:208} INFO - Processing /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2025-02-06T08:32:06.132+0000] {processor.py:186} INFO - Started process (PID=132) to work on /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T08:32:06.133+0000] {processor.py:914} INFO - Processing file /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-06T08:32:06.134+0000] {logging_mixin.py:190} INFO - [2025-02-06T08:32:06.134+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T08:32:06.138+0000] {logging_mixin.py:190} INFO - [2025-02-06T08:32:06.137+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-06T08:32:06.138+0000] {logging_mixin.py:190} INFO - [2025-02-06T08:32:06.138+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-06T08:32:06.139+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T08:32:06.158+0000] {processor.py:208} INFO - Processing /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2025-02-06T08:33:14.895+0000] {processor.py:186} INFO - Started process (PID=193) to work on /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T08:33:14.896+0000] {processor.py:914} INFO - Processing file /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-06T08:33:14.897+0000] {logging_mixin.py:190} INFO - [2025-02-06T08:33:14.897+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T08:33:14.901+0000] {logging_mixin.py:190} INFO - [2025-02-06T08:33:14.901+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-06T08:33:14.902+0000] {logging_mixin.py:190} INFO - [2025-02-06T08:33:14.902+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-06T08:33:14.903+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T08:33:14.921+0000] {processor.py:208} INFO - Processing /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2025-02-06T08:34:29.753+0000] {processor.py:186} INFO - Started process (PID=256) to work on /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T08:34:29.754+0000] {processor.py:914} INFO - Processing file /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-06T08:34:29.756+0000] {logging_mixin.py:190} INFO - [2025-02-06T08:34:29.755+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T08:34:29.766+0000] {logging_mixin.py:190} INFO - [2025-02-06T08:34:29.765+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-06T08:34:29.767+0000] {logging_mixin.py:190} INFO - [2025-02-06T08:34:29.767+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-06T08:34:29.768+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T08:34:29.800+0000] {processor.py:208} INFO - Processing /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.053 seconds
[2025-02-06T08:35:47.141+0000] {processor.py:186} INFO - Started process (PID=322) to work on /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T08:35:47.142+0000] {processor.py:914} INFO - Processing file /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-06T08:35:47.144+0000] {logging_mixin.py:190} INFO - [2025-02-06T08:35:47.143+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T08:35:47.149+0000] {logging_mixin.py:190} INFO - [2025-02-06T08:35:47.149+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-06T08:35:47.150+0000] {logging_mixin.py:190} INFO - [2025-02-06T08:35:47.150+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-06T08:35:47.150+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T08:35:47.167+0000] {processor.py:208} INFO - Processing /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
[2025-02-06T08:37:09.392+0000] {processor.py:186} INFO - Started process (PID=389) to work on /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T08:37:09.393+0000] {processor.py:914} INFO - Processing file /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-06T08:37:09.394+0000] {logging_mixin.py:190} INFO - [2025-02-06T08:37:09.394+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T08:37:09.400+0000] {logging_mixin.py:190} INFO - [2025-02-06T08:37:09.399+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-06T08:37:09.400+0000] {logging_mixin.py:190} INFO - [2025-02-06T08:37:09.400+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-06T08:37:09.401+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T08:37:09.429+0000] {processor.py:208} INFO - Processing /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2025-02-06T08:38:24.683+0000] {processor.py:186} INFO - Started process (PID=454) to work on /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T08:38:24.685+0000] {processor.py:914} INFO - Processing file /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-06T08:38:24.687+0000] {logging_mixin.py:190} INFO - [2025-02-06T08:38:24.686+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T08:38:24.695+0000] {logging_mixin.py:190} INFO - [2025-02-06T08:38:24.694+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-06T08:38:24.696+0000] {logging_mixin.py:190} INFO - [2025-02-06T08:38:24.695+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-06T08:38:24.696+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T08:38:24.715+0000] {processor.py:208} INFO - Processing /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.036 seconds
[2025-02-06T08:39:41.570+0000] {processor.py:186} INFO - Started process (PID=520) to work on /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T08:39:41.571+0000] {processor.py:914} INFO - Processing file /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-06T08:39:41.572+0000] {logging_mixin.py:190} INFO - [2025-02-06T08:39:41.572+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T08:39:41.579+0000] {logging_mixin.py:190} INFO - [2025-02-06T08:39:41.578+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-06T08:39:41.580+0000] {logging_mixin.py:190} INFO - [2025-02-06T08:39:41.579+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-06T08:39:41.580+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T08:39:41.600+0000] {processor.py:208} INFO - Processing /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2025-02-06T08:41:00.432+0000] {processor.py:186} INFO - Started process (PID=586) to work on /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T08:41:00.435+0000] {processor.py:914} INFO - Processing file /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-06T08:41:00.436+0000] {logging_mixin.py:190} INFO - [2025-02-06T08:41:00.436+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T08:41:00.443+0000] {logging_mixin.py:190} INFO - [2025-02-06T08:41:00.442+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-06T08:41:00.444+0000] {logging_mixin.py:190} INFO - [2025-02-06T08:41:00.443+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-06T08:41:00.444+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T08:41:00.467+0000] {processor.py:208} INFO - Processing /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.039 seconds
[2025-02-06T08:42:14.497+0000] {processor.py:186} INFO - Started process (PID=650) to work on /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T08:42:14.498+0000] {processor.py:914} INFO - Processing file /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-06T08:42:14.500+0000] {logging_mixin.py:190} INFO - [2025-02-06T08:42:14.499+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T08:42:14.506+0000] {logging_mixin.py:190} INFO - [2025-02-06T08:42:14.505+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-06T08:42:14.506+0000] {logging_mixin.py:190} INFO - [2025-02-06T08:42:14.506+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-06T08:42:14.507+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T08:42:14.526+0000] {processor.py:208} INFO - Processing /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2025-02-06T08:43:46.170+0000] {processor.py:186} INFO - Started process (PID=69) to work on /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T08:43:46.171+0000] {processor.py:914} INFO - Processing file /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-06T08:43:46.173+0000] {logging_mixin.py:190} INFO - [2025-02-06T08:43:46.173+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T08:43:46.177+0000] {logging_mixin.py:190} INFO - [2025-02-06T08:43:46.177+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-06T08:43:46.178+0000] {logging_mixin.py:190} INFO - [2025-02-06T08:43:46.178+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-06T08:43:46.178+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T08:43:46.197+0000] {processor.py:208} INFO - Processing /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
[2025-02-06T08:44:55.042+0000] {processor.py:186} INFO - Started process (PID=127) to work on /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T08:44:55.043+0000] {processor.py:914} INFO - Processing file /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-06T08:44:55.044+0000] {logging_mixin.py:190} INFO - [2025-02-06T08:44:55.044+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T08:44:55.048+0000] {logging_mixin.py:190} INFO - [2025-02-06T08:44:55.047+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-06T08:44:55.048+0000] {logging_mixin.py:190} INFO - [2025-02-06T08:44:55.048+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-06T08:44:55.049+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T08:44:55.068+0000] {processor.py:208} INFO - Processing /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
[2025-02-06T08:46:40.093+0000] {processor.py:186} INFO - Started process (PID=276) to work on /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T08:46:40.095+0000] {processor.py:914} INFO - Processing file /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-06T08:46:40.097+0000] {logging_mixin.py:190} INFO - [2025-02-06T08:46:40.096+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T08:46:40.101+0000] {logging_mixin.py:190} INFO - [2025-02-06T08:46:40.100+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-06T08:46:40.101+0000] {logging_mixin.py:190} INFO - [2025-02-06T08:46:40.101+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-06T08:46:40.102+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T08:46:40.127+0000] {processor.py:208} INFO - Processing /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.039 seconds
[2025-02-06T08:49:41.261+0000] {processor.py:186} INFO - Started process (PID=237) to work on /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T08:49:41.263+0000] {processor.py:914} INFO - Processing file /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-06T08:49:41.264+0000] {logging_mixin.py:190} INFO - [2025-02-06T08:49:41.264+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T08:49:41.268+0000] {logging_mixin.py:190} INFO - [2025-02-06T08:49:41.267+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-06T08:49:41.268+0000] {logging_mixin.py:190} INFO - [2025-02-06T08:49:41.268+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-06T08:49:41.268+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T08:49:41.286+0000] {processor.py:208} INFO - Processing /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2025-02-06T08:52:41.640+0000] {processor.py:186} INFO - Started process (PID=571) to work on /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T08:52:41.641+0000] {processor.py:914} INFO - Processing file /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-06T08:52:41.643+0000] {logging_mixin.py:190} INFO - [2025-02-06T08:52:41.642+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T08:52:41.646+0000] {logging_mixin.py:190} INFO - [2025-02-06T08:52:41.645+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-06T08:52:41.646+0000] {logging_mixin.py:190} INFO - [2025-02-06T08:52:41.646+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-06T08:52:41.647+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T08:52:41.666+0000] {processor.py:208} INFO - Processing /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
[2025-02-06T08:55:16.877+0000] {processor.py:186} INFO - Started process (PID=861) to work on /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T08:55:16.878+0000] {processor.py:914} INFO - Processing file /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-06T08:55:16.881+0000] {logging_mixin.py:190} INFO - [2025-02-06T08:55:16.880+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T08:55:16.885+0000] {logging_mixin.py:190} INFO - [2025-02-06T08:55:16.884+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-06T08:55:16.885+0000] {logging_mixin.py:190} INFO - [2025-02-06T08:55:16.885+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-06T08:55:16.886+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T08:55:16.904+0000] {processor.py:208} INFO - Processing /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2025-02-06T08:57:48.653+0000] {processor.py:186} INFO - Started process (PID=1122) to work on /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T08:57:48.654+0000] {processor.py:914} INFO - Processing file /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-06T08:57:48.657+0000] {logging_mixin.py:190} INFO - [2025-02-06T08:57:48.656+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T08:57:48.662+0000] {logging_mixin.py:190} INFO - [2025-02-06T08:57:48.661+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-06T08:57:48.662+0000] {logging_mixin.py:190} INFO - [2025-02-06T08:57:48.662+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-06T08:57:48.663+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T08:57:48.683+0000] {processor.py:208} INFO - Processing /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2025-02-06T09:02:31.744+0000] {processor.py:186} INFO - Started process (PID=238) to work on /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T09:02:31.746+0000] {processor.py:914} INFO - Processing file /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-06T09:02:31.747+0000] {logging_mixin.py:190} INFO - [2025-02-06T09:02:31.747+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T09:02:31.751+0000] {logging_mixin.py:190} INFO - [2025-02-06T09:02:31.750+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-06T09:02:31.751+0000] {logging_mixin.py:190} INFO - [2025-02-06T09:02:31.751+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-06T09:02:31.752+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T09:02:31.770+0000] {processor.py:208} INFO - Processing /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2025-02-06T09:05:28.033+0000] {processor.py:186} INFO - Started process (PID=153) to work on /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T09:05:28.035+0000] {processor.py:914} INFO - Processing file /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-06T09:05:28.038+0000] {logging_mixin.py:190} INFO - [2025-02-06T09:05:28.037+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T09:05:28.043+0000] {logging_mixin.py:190} INFO - [2025-02-06T09:05:28.042+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-06T09:05:28.043+0000] {logging_mixin.py:190} INFO - [2025-02-06T09:05:28.043+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-06T09:05:28.044+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T09:05:28.066+0000] {processor.py:208} INFO - Processing /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.040 seconds
[2025-02-06T09:08:31.723+0000] {processor.py:186} INFO - Started process (PID=495) to work on /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T09:08:31.724+0000] {processor.py:914} INFO - Processing file /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-06T09:08:31.726+0000] {logging_mixin.py:190} INFO - [2025-02-06T09:08:31.726+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T09:08:31.730+0000] {logging_mixin.py:190} INFO - [2025-02-06T09:08:31.729+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-06T09:08:31.730+0000] {logging_mixin.py:190} INFO - [2025-02-06T09:08:31.730+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-06T09:08:31.731+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T09:08:31.748+0000] {processor.py:208} INFO - Processing /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2025-02-06T09:10:47.302+0000] {processor.py:186} INFO - Started process (PID=752) to work on /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T09:10:47.303+0000] {processor.py:914} INFO - Processing file /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-06T09:10:47.306+0000] {logging_mixin.py:190} INFO - [2025-02-06T09:10:47.305+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T09:10:47.310+0000] {logging_mixin.py:190} INFO - [2025-02-06T09:10:47.309+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-06T09:10:47.310+0000] {logging_mixin.py:190} INFO - [2025-02-06T09:10:47.310+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-06T09:10:47.311+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T09:10:47.337+0000] {processor.py:208} INFO - Processing /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.040 seconds
[2025-02-06T09:13:13.753+0000] {processor.py:186} INFO - Started process (PID=1023) to work on /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T09:13:13.754+0000] {processor.py:914} INFO - Processing file /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-06T09:13:13.756+0000] {logging_mixin.py:190} INFO - [2025-02-06T09:13:13.756+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T09:13:13.760+0000] {logging_mixin.py:190} INFO - [2025-02-06T09:13:13.759+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-06T09:13:13.760+0000] {logging_mixin.py:190} INFO - [2025-02-06T09:13:13.760+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-06T09:13:13.761+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T09:13:13.782+0000] {processor.py:208} INFO - Processing /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2025-02-06T09:15:41.501+0000] {processor.py:186} INFO - Started process (PID=1290) to work on /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T09:15:41.502+0000] {processor.py:914} INFO - Processing file /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-06T09:15:41.504+0000] {logging_mixin.py:190} INFO - [2025-02-06T09:15:41.503+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T09:15:41.507+0000] {logging_mixin.py:190} INFO - [2025-02-06T09:15:41.506+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-06T09:15:41.507+0000] {logging_mixin.py:190} INFO - [2025-02-06T09:15:41.507+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-06T09:15:41.507+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T09:15:41.524+0000] {processor.py:208} INFO - Processing /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2025-02-06T09:17:47.669+0000] {processor.py:186} INFO - Started process (PID=1535) to work on /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T09:17:47.670+0000] {processor.py:914} INFO - Processing file /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-06T09:17:47.673+0000] {logging_mixin.py:190} INFO - [2025-02-06T09:17:47.672+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T09:17:47.676+0000] {logging_mixin.py:190} INFO - [2025-02-06T09:17:47.676+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-06T09:17:47.677+0000] {logging_mixin.py:190} INFO - [2025-02-06T09:17:47.677+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-06T09:17:47.677+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T09:17:47.698+0000] {processor.py:208} INFO - Processing /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.036 seconds
[2025-02-06T09:20:24.214+0000] {processor.py:186} INFO - Started process (PID=1796) to work on /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T09:20:24.215+0000] {processor.py:914} INFO - Processing file /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-06T09:20:24.217+0000] {logging_mixin.py:190} INFO - [2025-02-06T09:20:24.216+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T09:20:24.221+0000] {logging_mixin.py:190} INFO - [2025-02-06T09:20:24.220+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-06T09:20:24.221+0000] {logging_mixin.py:190} INFO - [2025-02-06T09:20:24.221+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-06T09:20:24.222+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T09:20:24.240+0000] {processor.py:208} INFO - Processing /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
[2025-02-06T09:23:06.609+0000] {processor.py:186} INFO - Started process (PID=2067) to work on /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T09:23:06.610+0000] {processor.py:914} INFO - Processing file /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-06T09:23:06.612+0000] {logging_mixin.py:190} INFO - [2025-02-06T09:23:06.611+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T09:23:06.616+0000] {logging_mixin.py:190} INFO - [2025-02-06T09:23:06.615+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-06T09:23:06.616+0000] {logging_mixin.py:190} INFO - [2025-02-06T09:23:06.616+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-06T09:23:06.617+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T09:23:06.634+0000] {processor.py:208} INFO - Processing /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2025-02-06T09:26:11.958+0000] {processor.py:186} INFO - Started process (PID=223) to work on /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T09:26:11.959+0000] {processor.py:914} INFO - Processing file /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-06T09:26:11.960+0000] {logging_mixin.py:190} INFO - [2025-02-06T09:26:11.960+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T09:26:11.964+0000] {logging_mixin.py:190} INFO - [2025-02-06T09:26:11.963+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-06T09:26:11.964+0000] {logging_mixin.py:190} INFO - [2025-02-06T09:26:11.964+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-06T09:26:11.965+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T09:26:11.997+0000] {processor.py:208} INFO - Processing /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2025-02-06T09:32:45.927+0000] {processor.py:186} INFO - Started process (PID=421) to work on /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T09:32:45.929+0000] {processor.py:914} INFO - Processing file /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-06T09:32:45.930+0000] {logging_mixin.py:190} INFO - [2025-02-06T09:32:45.930+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T09:32:45.935+0000] {logging_mixin.py:190} INFO - [2025-02-06T09:32:45.934+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-06T09:32:45.936+0000] {logging_mixin.py:190} INFO - [2025-02-06T09:32:45.935+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-06T09:32:45.936+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T09:32:45.957+0000] {processor.py:208} INFO - Processing /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2025-02-06T09:38:08.007+0000] {processor.py:186} INFO - Started process (PID=1003) to work on /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T09:38:08.009+0000] {processor.py:914} INFO - Processing file /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-06T09:38:08.013+0000] {logging_mixin.py:190} INFO - [2025-02-06T09:38:08.012+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T09:38:08.020+0000] {logging_mixin.py:190} INFO - [2025-02-06T09:38:08.020+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-06T09:38:08.021+0000] {logging_mixin.py:190} INFO - [2025-02-06T09:38:08.021+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-06T09:38:08.021+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T09:38:08.041+0000] {processor.py:208} INFO - Processing /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.039 seconds
[2025-02-06T09:42:43.812+0000] {processor.py:186} INFO - Started process (PID=1480) to work on /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T09:42:43.813+0000] {processor.py:914} INFO - Processing file /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-06T09:42:43.815+0000] {logging_mixin.py:190} INFO - [2025-02-06T09:42:43.815+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T09:42:43.819+0000] {logging_mixin.py:190} INFO - [2025-02-06T09:42:43.818+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-06T09:42:43.819+0000] {logging_mixin.py:190} INFO - [2025-02-06T09:42:43.819+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-06T09:42:43.820+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T09:42:43.838+0000] {processor.py:208} INFO - Processing /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2025-02-06T09:50:14.645+0000] {processor.py:186} INFO - Started process (PID=404) to work on /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T09:50:14.646+0000] {processor.py:914} INFO - Processing file /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-06T09:50:14.648+0000] {logging_mixin.py:190} INFO - [2025-02-06T09:50:14.647+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T09:50:14.652+0000] {logging_mixin.py:190} INFO - [2025-02-06T09:50:14.651+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-06T09:50:14.652+0000] {logging_mixin.py:190} INFO - [2025-02-06T09:50:14.652+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-06T09:50:14.653+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T09:50:14.671+0000] {processor.py:208} INFO - Processing /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2025-02-06T09:55:33.923+0000] {processor.py:186} INFO - Started process (PID=971) to work on /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T09:55:33.925+0000] {processor.py:914} INFO - Processing file /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-06T09:55:33.927+0000] {logging_mixin.py:190} INFO - [2025-02-06T09:55:33.926+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T09:55:33.930+0000] {logging_mixin.py:190} INFO - [2025-02-06T09:55:33.930+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-06T09:55:33.931+0000] {logging_mixin.py:190} INFO - [2025-02-06T09:55:33.931+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-06T09:55:33.931+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T09:55:33.950+0000] {processor.py:208} INFO - Processing /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
[2025-02-06T09:59:41.812+0000] {processor.py:186} INFO - Started process (PID=1446) to work on /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T09:59:41.813+0000] {processor.py:914} INFO - Processing file /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-06T09:59:41.816+0000] {logging_mixin.py:190} INFO - [2025-02-06T09:59:41.815+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T09:59:41.819+0000] {logging_mixin.py:190} INFO - [2025-02-06T09:59:41.819+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-06T09:59:41.820+0000] {logging_mixin.py:190} INFO - [2025-02-06T09:59:41.820+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-06T09:59:41.820+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T09:59:41.840+0000] {processor.py:208} INFO - Processing /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2025-02-06T10:04:24.202+0000] {processor.py:186} INFO - Started process (PID=1934) to work on /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T10:04:24.204+0000] {processor.py:914} INFO - Processing file /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-06T10:04:24.206+0000] {logging_mixin.py:190} INFO - [2025-02-06T10:04:24.205+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T10:04:24.209+0000] {logging_mixin.py:190} INFO - [2025-02-06T10:04:24.209+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-06T10:04:24.210+0000] {logging_mixin.py:190} INFO - [2025-02-06T10:04:24.209+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-06T10:04:24.210+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T10:04:24.234+0000] {processor.py:208} INFO - Processing /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.036 seconds
[2025-02-06T10:06:17.422+0000] {processor.py:186} INFO - Started process (PID=2077) to work on /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T10:06:17.423+0000] {processor.py:914} INFO - Processing file /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-06T10:06:17.424+0000] {logging_mixin.py:190} INFO - [2025-02-06T10:06:17.424+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T10:06:17.429+0000] {logging_mixin.py:190} INFO - [2025-02-06T10:06:17.428+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-06T10:06:17.429+0000] {logging_mixin.py:190} INFO - [2025-02-06T10:06:17.429+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-06T10:06:17.430+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T10:06:17.449+0000] {processor.py:208} INFO - Processing /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2025-02-06T10:14:43.428+0000] {processor.py:186} INFO - Started process (PID=2934) to work on /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T10:14:43.429+0000] {processor.py:914} INFO - Processing file /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-06T10:14:43.431+0000] {logging_mixin.py:190} INFO - [2025-02-06T10:14:43.431+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T10:14:43.437+0000] {logging_mixin.py:190} INFO - [2025-02-06T10:14:43.436+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-06T10:14:43.437+0000] {logging_mixin.py:190} INFO - [2025-02-06T10:14:43.437+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-06T10:14:43.438+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T10:14:43.465+0000] {processor.py:208} INFO - Processing /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2025-02-06T10:20:33.876+0000] {processor.py:186} INFO - Started process (PID=3540) to work on /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T10:20:33.877+0000] {processor.py:914} INFO - Processing file /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-06T10:20:33.879+0000] {logging_mixin.py:190} INFO - [2025-02-06T10:20:33.878+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T10:20:33.882+0000] {logging_mixin.py:190} INFO - [2025-02-06T10:20:33.882+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-06T10:20:33.883+0000] {logging_mixin.py:190} INFO - [2025-02-06T10:20:33.883+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-06T10:20:33.884+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T10:20:33.904+0000] {processor.py:208} INFO - Processing /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2025-02-06T10:24:15.840+0000] {processor.py:186} INFO - Started process (PID=3897) to work on /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T10:24:15.841+0000] {processor.py:914} INFO - Processing file /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-06T10:24:15.843+0000] {logging_mixin.py:190} INFO - [2025-02-06T10:24:15.842+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T10:24:15.847+0000] {logging_mixin.py:190} INFO - [2025-02-06T10:24:15.846+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-06T10:24:15.848+0000] {logging_mixin.py:190} INFO - [2025-02-06T10:24:15.847+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-06T10:24:15.848+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T10:24:15.869+0000] {processor.py:208} INFO - Processing /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2025-02-06T11:42:15.025+0000] {processor.py:186} INFO - Started process (PID=847) to work on /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T11:42:15.028+0000] {processor.py:914} INFO - Processing file /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-06T11:42:15.030+0000] {logging_mixin.py:190} INFO - [2025-02-06T11:42:15.029+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T11:42:15.033+0000] {logging_mixin.py:190} INFO - [2025-02-06T11:42:15.033+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-06T11:42:15.034+0000] {logging_mixin.py:190} INFO - [2025-02-06T11:42:15.034+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-06T11:42:15.035+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T11:42:15.054+0000] {processor.py:208} INFO - Processing /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2025-02-06T11:46:48.444+0000] {processor.py:186} INFO - Started process (PID=1842) to work on /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T11:46:48.446+0000] {processor.py:914} INFO - Processing file /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-06T11:46:48.449+0000] {logging_mixin.py:190} INFO - [2025-02-06T11:46:48.449+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T11:46:48.459+0000] {logging_mixin.py:190} INFO - [2025-02-06T11:46:48.459+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-06T11:46:48.460+0000] {logging_mixin.py:190} INFO - [2025-02-06T11:46:48.460+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-06T11:46:48.461+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T11:46:48.495+0000] {processor.py:208} INFO - Processing /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.056 seconds
[2025-02-06T11:50:34.300+0000] {processor.py:186} INFO - Started process (PID=2755) to work on /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T11:50:34.302+0000] {processor.py:914} INFO - Processing file /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-06T11:50:34.303+0000] {logging_mixin.py:190} INFO - [2025-02-06T11:50:34.303+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T11:50:34.312+0000] {logging_mixin.py:190} INFO - [2025-02-06T11:50:34.311+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-06T11:50:34.312+0000] {logging_mixin.py:190} INFO - [2025-02-06T11:50:34.312+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-06T11:50:34.313+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T11:50:34.418+0000] {processor.py:208} INFO - Processing /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.125 seconds
[2025-02-06T11:54:22.044+0000] {processor.py:186} INFO - Started process (PID=3728) to work on /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T11:54:22.046+0000] {processor.py:914} INFO - Processing file /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-06T11:54:22.049+0000] {logging_mixin.py:190} INFO - [2025-02-06T11:54:22.048+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T11:54:22.061+0000] {logging_mixin.py:190} INFO - [2025-02-06T11:54:22.060+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-06T11:54:22.062+0000] {logging_mixin.py:190} INFO - [2025-02-06T11:54:22.061+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-06T11:54:22.062+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T11:54:22.092+0000] {processor.py:208} INFO - Processing /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.054 seconds
[2025-02-06T12:05:47.219+0000] {processor.py:186} INFO - Started process (PID=865) to work on /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T12:05:47.220+0000] {processor.py:914} INFO - Processing file /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-06T12:05:47.222+0000] {logging_mixin.py:190} INFO - [2025-02-06T12:05:47.221+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T12:05:47.225+0000] {logging_mixin.py:190} INFO - [2025-02-06T12:05:47.224+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-06T12:05:47.225+0000] {logging_mixin.py:190} INFO - [2025-02-06T12:05:47.225+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-06T12:05:47.226+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T12:05:47.245+0000] {processor.py:208} INFO - Processing /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2025-02-06T12:08:38.328+0000] {processor.py:186} INFO - Started process (PID=1899) to work on /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T12:08:38.329+0000] {processor.py:914} INFO - Processing file /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-06T12:08:38.331+0000] {logging_mixin.py:190} INFO - [2025-02-06T12:08:38.331+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T12:08:38.337+0000] {logging_mixin.py:190} INFO - [2025-02-06T12:08:38.336+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-06T12:08:38.337+0000] {logging_mixin.py:190} INFO - [2025-02-06T12:08:38.337+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-06T12:08:38.338+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T12:08:38.357+0000] {processor.py:208} INFO - Processing /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2025-02-06T12:18:11.978+0000] {processor.py:186} INFO - Started process (PID=108) to work on /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T12:18:11.979+0000] {processor.py:914} INFO - Processing file /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-06T12:18:11.981+0000] {logging_mixin.py:190} INFO - [2025-02-06T12:18:11.981+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T12:18:11.985+0000] {logging_mixin.py:190} INFO - [2025-02-06T12:18:11.984+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-06T12:18:11.985+0000] {logging_mixin.py:190} INFO - [2025-02-06T12:18:11.985+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-06T12:18:11.986+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T12:18:12.016+0000] {processor.py:208} INFO - Processing /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2025-02-06T12:22:16.149+0000] {processor.py:186} INFO - Started process (PID=392) to work on /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T12:22:16.151+0000] {processor.py:914} INFO - Processing file /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-06T12:22:16.152+0000] {logging_mixin.py:190} INFO - [2025-02-06T12:22:16.152+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T12:22:16.156+0000] {logging_mixin.py:190} INFO - [2025-02-06T12:22:16.156+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-06T12:22:16.157+0000] {logging_mixin.py:190} INFO - [2025-02-06T12:22:16.157+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-06T12:22:16.157+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T12:22:16.178+0000] {processor.py:208} INFO - Processing /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2025-02-06T12:24:25.289+0000] {processor.py:186} INFO - Started process (PID=1196) to work on /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T12:24:25.290+0000] {processor.py:914} INFO - Processing file /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-06T12:24:25.292+0000] {logging_mixin.py:190} INFO - [2025-02-06T12:24:25.292+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T12:24:25.297+0000] {logging_mixin.py:190} INFO - [2025-02-06T12:24:25.296+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-06T12:24:25.297+0000] {logging_mixin.py:190} INFO - [2025-02-06T12:24:25.297+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-06T12:24:25.298+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T12:24:25.319+0000] {processor.py:208} INFO - Processing /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2025-02-06T12:27:37.103+0000] {processor.py:186} INFO - Started process (PID=2634) to work on /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T12:27:37.104+0000] {processor.py:914} INFO - Processing file /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-06T12:27:37.105+0000] {logging_mixin.py:190} INFO - [2025-02-06T12:27:37.105+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T12:27:37.109+0000] {logging_mixin.py:190} INFO - [2025-02-06T12:27:37.109+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-06T12:27:37.110+0000] {logging_mixin.py:190} INFO - [2025-02-06T12:27:37.110+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-06T12:27:37.110+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T12:27:37.131+0000] {processor.py:208} INFO - Processing /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2025-02-06T12:31:27.970+0000] {processor.py:186} INFO - Started process (PID=4647) to work on /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T12:31:27.971+0000] {processor.py:914} INFO - Processing file /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-06T12:31:27.973+0000] {logging_mixin.py:190} INFO - [2025-02-06T12:31:27.972+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T12:31:27.977+0000] {logging_mixin.py:190} INFO - [2025-02-06T12:31:27.976+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-06T12:31:27.977+0000] {logging_mixin.py:190} INFO - [2025-02-06T12:31:27.977+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-06T12:31:27.977+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T12:31:27.999+0000] {processor.py:208} INFO - Processing /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2025-02-06T12:35:36.537+0000] {processor.py:186} INFO - Started process (PID=6803) to work on /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T12:35:36.538+0000] {processor.py:914} INFO - Processing file /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-06T12:35:36.540+0000] {logging_mixin.py:190} INFO - [2025-02-06T12:35:36.540+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T12:35:36.546+0000] {logging_mixin.py:190} INFO - [2025-02-06T12:35:36.545+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-06T12:35:36.547+0000] {logging_mixin.py:190} INFO - [2025-02-06T12:35:36.547+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-06T12:35:36.547+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T12:35:36.571+0000] {processor.py:208} INFO - Processing /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.039 seconds
[2025-02-06T12:39:45.397+0000] {processor.py:186} INFO - Started process (PID=8889) to work on /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T12:39:45.398+0000] {processor.py:914} INFO - Processing file /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-06T12:39:45.400+0000] {logging_mixin.py:190} INFO - [2025-02-06T12:39:45.400+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T12:39:45.404+0000] {logging_mixin.py:190} INFO - [2025-02-06T12:39:45.403+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-06T12:39:45.404+0000] {logging_mixin.py:190} INFO - [2025-02-06T12:39:45.404+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-06T12:39:45.404+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T12:39:45.421+0000] {processor.py:208} INFO - Processing /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2025-02-06T12:43:52.732+0000] {processor.py:186} INFO - Started process (PID=11026) to work on /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T12:43:52.733+0000] {processor.py:914} INFO - Processing file /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-06T12:43:52.735+0000] {logging_mixin.py:190} INFO - [2025-02-06T12:43:52.734+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T12:43:52.740+0000] {logging_mixin.py:190} INFO - [2025-02-06T12:43:52.739+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-06T12:43:52.740+0000] {logging_mixin.py:190} INFO - [2025-02-06T12:43:52.740+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-06T12:43:52.741+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T12:43:52.759+0000] {processor.py:208} INFO - Processing /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
[2025-02-06T12:48:22.970+0000] {processor.py:186} INFO - Started process (PID=13161) to work on /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T12:48:22.971+0000] {processor.py:914} INFO - Processing file /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-06T12:48:22.974+0000] {logging_mixin.py:190} INFO - [2025-02-06T12:48:22.973+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T12:48:22.978+0000] {logging_mixin.py:190} INFO - [2025-02-06T12:48:22.978+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-06T12:48:22.979+0000] {logging_mixin.py:190} INFO - [2025-02-06T12:48:22.978+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-06T12:48:22.979+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T12:48:22.998+0000] {processor.py:208} INFO - Processing /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2025-02-06T12:58:50.434+0000] {processor.py:186} INFO - Started process (PID=416) to work on /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T12:58:50.435+0000] {processor.py:914} INFO - Processing file /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-06T12:58:50.437+0000] {logging_mixin.py:190} INFO - [2025-02-06T12:58:50.437+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T12:58:50.441+0000] {logging_mixin.py:190} INFO - [2025-02-06T12:58:50.441+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-06T12:58:50.442+0000] {logging_mixin.py:190} INFO - [2025-02-06T12:58:50.442+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-06T12:58:50.442+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T12:58:50.616+0000] {processor.py:208} INFO - Processing /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.186 seconds
[2025-02-06T13:02:20.803+0000] {processor.py:186} INFO - Started process (PID=1392) to work on /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T13:02:20.804+0000] {processor.py:914} INFO - Processing file /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-06T13:02:20.806+0000] {logging_mixin.py:190} INFO - [2025-02-06T13:02:20.806+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T13:02:20.813+0000] {logging_mixin.py:190} INFO - [2025-02-06T13:02:20.811+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-06T13:02:20.814+0000] {logging_mixin.py:190} INFO - [2025-02-06T13:02:20.813+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-06T13:02:20.815+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T13:02:20.839+0000] {processor.py:208} INFO - Processing /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.041 seconds
[2025-02-06T13:04:51.234+0000] {processor.py:186} INFO - Started process (PID=2223) to work on /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T13:04:51.235+0000] {processor.py:914} INFO - Processing file /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-06T13:04:51.237+0000] {logging_mixin.py:190} INFO - [2025-02-06T13:04:51.237+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T13:04:51.242+0000] {logging_mixin.py:190} INFO - [2025-02-06T13:04:51.242+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-06T13:04:51.243+0000] {logging_mixin.py:190} INFO - [2025-02-06T13:04:51.243+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-06T13:04:51.244+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T13:04:51.266+0000] {processor.py:208} INFO - Processing /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.036 seconds
[2025-02-06T13:19:43.146+0000] {processor.py:186} INFO - Started process (PID=484) to work on /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T13:19:43.147+0000] {processor.py:914} INFO - Processing file /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-06T13:19:43.149+0000] {logging_mixin.py:190} INFO - [2025-02-06T13:19:43.149+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T13:19:43.154+0000] {logging_mixin.py:190} INFO - [2025-02-06T13:19:43.153+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-06T13:19:43.154+0000] {logging_mixin.py:190} INFO - [2025-02-06T13:19:43.154+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-06T13:19:43.154+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T13:19:43.178+0000] {processor.py:208} INFO - Processing /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2025-02-06T13:23:40.528+0000] {processor.py:186} INFO - Started process (PID=1993) to work on /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T13:23:40.529+0000] {processor.py:914} INFO - Processing file /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-06T13:23:40.531+0000] {logging_mixin.py:190} INFO - [2025-02-06T13:23:40.531+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T13:23:40.535+0000] {logging_mixin.py:190} INFO - [2025-02-06T13:23:40.534+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-06T13:23:40.536+0000] {logging_mixin.py:190} INFO - [2025-02-06T13:23:40.535+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-06T13:23:40.536+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T13:23:40.558+0000] {processor.py:208} INFO - Processing /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2025-02-06T13:28:00.541+0000] {processor.py:186} INFO - Started process (PID=3901) to work on /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T13:28:00.542+0000] {processor.py:914} INFO - Processing file /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-06T13:28:00.545+0000] {logging_mixin.py:190} INFO - [2025-02-06T13:28:00.545+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T13:28:00.552+0000] {logging_mixin.py:190} INFO - [2025-02-06T13:28:00.551+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-06T13:28:00.553+0000] {logging_mixin.py:190} INFO - [2025-02-06T13:28:00.553+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-06T13:28:00.553+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T13:28:00.576+0000] {processor.py:208} INFO - Processing /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2025-02-06T13:32:06.586+0000] {processor.py:186} INFO - Started process (PID=5533) to work on /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T13:32:06.587+0000] {processor.py:914} INFO - Processing file /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-06T13:32:06.589+0000] {logging_mixin.py:190} INFO - [2025-02-06T13:32:06.588+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T13:32:06.593+0000] {logging_mixin.py:190} INFO - [2025-02-06T13:32:06.593+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-06T13:32:06.594+0000] {logging_mixin.py:190} INFO - [2025-02-06T13:32:06.594+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-06T13:32:06.594+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-06T13:32:06.615+0000] {processor.py:208} INFO - Processing /opt/conda/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.036 seconds
